import { createTamagui } from "@tamagui/core";
import {
  Inter_400Regular,
  Inter_600SemiBold,
  Inter_700Bold,
} from "@expo-google-fonts/inter";
import {
  Poppins_600SemiBold,
  Poppins_700Bold,
} from "@expo-google-fonts/poppins";
import { tokens } from "../tokens";

const lightTheme = {
  background: tokens.color.backgroundLight,
  backgroundHover: "#F0F0F0",
  backgroundPress: "#E8E8E8",
  backgroundFocus: "#F0F0F0",
  backgroundStrong: tokens.color.surfaceLight,
  backgroundTransparent: "transparent",
  color: tokens.color.textLight,
  colorHover: "#333333",
  colorPress: "#111111",
  colorFocus: "#333333",
  colorTransparent: "transparent",
  borderColor: "#D8D0B0",
  borderColorHover: "#C8BFA0",
  borderColorFocus: tokens.color.primary,
  borderColorPress: "#B8AF90",
  placeholderColor: "#9A9470",
  outlineColor: tokens.color.primary,
  primary: tokens.color.primary,
  secondary: tokens.color.secondary,
  surface: tokens.color.surfaceLight,
  shadowColor: "rgba(0,0,0,0.12)",
  // Shadcn-style semantic
  card: tokens.color.surfaceLight,
  input: "#EDE8D0",
};

const darkTheme = {
  background: tokens.color.backgroundDark,
  backgroundHover: "#222810",
  backgroundPress: "#2A3014",
  backgroundFocus: "#222810",
  backgroundStrong: tokens.color.surfaceDark,
  backgroundTransparent: "transparent",
  color: tokens.color.textDark,
  colorHover: "#E8EDD0",
  colorPress: "#FEFEF5",
  colorFocus: "#E8EDD0",
  colorTransparent: "transparent",
  borderColor: "#3A4020",
  borderColorHover: "#4A5028",
  borderColorFocus: tokens.color.secondary,
  borderColorPress: "#585E34",
  placeholderColor: "#6E7848",
  outlineColor: tokens.color.secondary,
  primary: tokens.color.secondary,
  secondary: tokens.color.primary,
  surface: tokens.color.surfaceDark,
  shadowColor: "rgba(0,0,0,0.4)",
  card: tokens.color.surfaceDark,
  input: "#222810",
};

const config = createTamagui({
  tokens,
  themes: {
    light: lightTheme,
    dark: darkTheme,
  },
  fonts: {
    body: {
      family: "Inter",
      size: {
        sm: 14,
        md: 16,
        lg: 20,
        xl: 28,
        xxl: 36,
        1: 11,
        2: 12,
        3: 13,
        4: 14,
        5: 15,
        6: 16,
        7: 20,
        8: 23,
        9: 30,
        10: 46,
        true: 16,
      },
      lineHeight: {
        sm: 20,
        md: 24,
        lg: 28,
        xl: 36,
        1: 16,
        2: 18,
        3: 20,
        4: 22,
        5: 22,
        6: 24,
        7: 28,
        8: 32,
        9: 40,
        10: 56,
        true: 24,
      },
      weight: {
        regular: "400",
        semibold: "600",
        bold: "700",
        4: "400",
        5: "400",
        6: "400",
        true: "400",
      },
      letterSpacing: {
        4: 0,
        5: 0,
        6: 0,
        true: 0,
      },
      face: {
        400: { normal: "Inter_400Regular" },
        600: { normal: "Inter_600SemiBold" },
        700: { normal: "Inter_700Bold" },
      },
    },
    heading: {
      family: "Poppins",
      size: {
        sm: 14,
        md: 16,
        lg: 20,
        xl: 28,
        xxl: 36,
        1: 11,
        2: 12,
        3: 13,
        4: 14,
        5: 15,
        6: 16,
        7: 20,
        8: 23,
        9: 30,
        10: 46,
        true: 20,
      },
      lineHeight: {
        sm: 20,
        md: 24,
        lg: 28,
        xl: 36,
        1: 16,
        2: 18,
        3: 20,
        4: 22,
        5: 22,
        6: 24,
        7: 28,
        8: 32,
        9: 40,
        10: 56,
        true: 28,
      },
      weight: {
        regular: "600",
        semibold: "600",
        bold: "700",
        4: "600",
        5: "600",
        6: "600",
        true: "600",
      },
      letterSpacing: {
        4: 0,
        5: 0,
        6: 0,
        true: -0.5,
      },
      face: {
        600: { normal: "Poppins_600SemiBold" },
        700: { normal: "Poppins_700Bold" },
      },
    },
  },
  shorthands: {
    px: "paddingHorizontal",
    py: "paddingVertical",
    p: "padding",
    m: "margin",
    mx: "marginHorizontal",
    my: "marginVertical",
    mt: "marginTop",
    mb: "marginBottom",
    ml: "marginLeft",
    mr: "marginRight",
    pt: "paddingTop",
    pb: "paddingBottom",
    pl: "paddingLeft",
    pr: "paddingRight",
    f: "flex",
    fd: "flexDirection",
    fw: "flexWrap",
    ai: "alignItems",
    jc: "justifyContent",
    bg: "backgroundColor",
    br: "borderRadius",
    boc: "borderColor",
    bw: "borderWidth",
    w: "width",
    h: "height",
    maw: "maxWidth",
    mah: "maxHeight",
    miw: "minWidth",
    mih: "minHeight",
    pos: "position",
    zi: "zIndex",
    ov: "overflow",
    op: "opacity",
  } as const,
  media: {
    xs: { maxWidth: 660 },
    sm: { maxWidth: 800 },
    md: { maxWidth: 1020 },
    lg: { maxWidth: 1280 },
    xl: { maxWidth: 1650 },
    xxl: { minWidth: 1651 },
    gtXs: { minWidth: 660 + 1 },
    gtSm: { minWidth: 800 + 1 },
    gtMd: { minWidth: 1020 + 1 },
    gtLg: { minWidth: 1280 + 1 },
  },
});

export type AppConfig = typeof config;

declare module "tamagui" {
  // eslint-disable-next-line @typescript-eslint/no-empty-object-type
  interface TamaguiCustomConfig extends AppConfig {}
}

export default config;

// Font assets export for useFonts
export const fontAssets = {
  Inter_400Regular,
  Inter_600SemiBold,
  Inter_700Bold,
  Poppins_600SemiBold,
  Poppins_700Bold,
};
