import { createTamagui, createTokens } from "@tamagui/core";
import { themes as defaultThemes } from "@tamagui/themes";
import { Inter_400Regular, Inter_600SemiBold, Inter_700Bold } from "@expo-google-fonts/inter";
import {
  Poppins_600SemiBold,
  Poppins_700Bold,
} from "@expo-google-fonts/poppins";

const tokens = createTokens({
  color: {
    // Brand
    primary: "#6C5CE7",
    secondary: "#A29BFE",

    // Emotion palette
    emotionHappy: "#FFD700",
    emotionSad: "#4A90D9",
    emotionAnxious: "#FF6B6B",
    emotionAngry: "#E74C3C",
    emotionNeutral: "#95A5A6",
    emotionGrateful: "#2ECC71",
    emotionTired: "#8E44AD",
    emotionMotivated: "#F39C12",

    // Semantic – light defaults (overridden by themes)
    backgroundLight: "#FAFAFA",
    backgroundDark: "#1A1A2E",
    surfaceLight: "#FFFFFF",
    surfaceDark: "#16213E",
    textLight: "#1A1A2E",
    textDark: "#FAFAFA",

    // Error / neutral
    error: "#E74C3C",
    white: "#FFFFFF",
    black: "#000000",
    transparent: "transparent",
  },

  space: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
    xxl: 48,
    // Required size tokens
    0: 0,
    1: 4,
    2: 8,
    3: 12,
    4: 16,
    5: 20,
    6: 24,
    8: 32,
    10: 40,
    12: 48,
    true: 16,
  },

  size: {
    xs: 28,
    sm: 36,
    md: 44,
    lg: 52,
    xl: 60,
    0: 0,
    1: 4,
    2: 8,
    3: 12,
    4: 16,
    5: 20,
    6: 24,
    8: 32,
    10: 40,
    12: 48,
    true: 44,
  },

  radius: {
    sm: 8,
    md: 12,
    lg: 16,
    xl: 24,
    full: 9999,
    0: 0,
    1: 4,
    2: 8,
    3: 12,
    4: 16,
    true: 12,
  },

  zIndex: {
    0: 0,
    1: 100,
    2: 200,
    3: 300,
    4: 400,
    5: 500,
  },
});

const lightTheme = {
  background: tokens.color.backgroundLight,
  backgroundHover: "#F0F0F0",
  backgroundPress: "#E8E8E8",
  backgroundFocus: "#F0F0F0",
  backgroundStrong: tokens.color.surfaceLight,
  backgroundTransparent: "transparent",
  color: tokens.color.textLight,
  colorHover: "#333333",
  colorPress: "#111111",
  colorFocus: "#333333",
  colorTransparent: "transparent",
  borderColor: "#E0E0E0",
  borderColorHover: "#CCCCCC",
  borderColorFocus: tokens.color.primary,
  borderColorPress: "#BBBBBB",
  placeholderColor: "#9E9E9E",
  outlineColor: tokens.color.primary,
  primary: tokens.color.primary,
  secondary: tokens.color.secondary,
  surface: tokens.color.surfaceLight,
  shadowColor: "rgba(0,0,0,0.1)",
  // Shadcn-style semantic
  card: tokens.color.surfaceLight,
  input: "#F5F5F5",
};

const darkTheme = {
  background: tokens.color.backgroundDark,
  backgroundHover: "#1E1E3E",
  backgroundPress: "#252545",
  backgroundFocus: "#1E1E3E",
  backgroundStrong: tokens.color.surfaceDark,
  backgroundTransparent: "transparent",
  color: tokens.color.textDark,
  colorHover: "#E0E0E0",
  colorPress: "#FFFFFF",
  colorFocus: "#E0E0E0",
  colorTransparent: "transparent",
  borderColor: "#2E2E4E",
  borderColorHover: "#3E3E5E",
  borderColorFocus: tokens.color.secondary,
  borderColorPress: "#4E4E6E",
  placeholderColor: "#6E6E8E",
  outlineColor: tokens.color.secondary,
  primary: tokens.color.secondary,
  secondary: tokens.color.primary,
  surface: tokens.color.surfaceDark,
  shadowColor: "rgba(0,0,0,0.4)",
  card: tokens.color.surfaceDark,
  input: "#1E1E3E",
};

const config = createTamagui({
  tokens,
  themes: {
    light: lightTheme,
    dark: darkTheme,
  },
  fonts: {
    body: {
      family: "Inter",
      size: {
        sm: 14,
        md: 16,
        lg: 20,
        xl: 28,
        xxl: 36,
        1: 11,
        2: 12,
        3: 13,
        4: 14,
        5: 15,
        6: 16,
        7: 20,
        8: 23,
        9: 30,
        10: 46,
        true: 16,
      },
      lineHeight: {
        sm: 20,
        md: 24,
        lg: 28,
        xl: 36,
        1: 16,
        2: 18,
        3: 20,
        4: 22,
        5: 22,
        6: 24,
        7: 28,
        8: 32,
        9: 40,
        10: 56,
        true: 24,
      },
      weight: {
        regular: "400",
        semibold: "600",
        bold: "700",
        4: "400",
        5: "400",
        6: "400",
        true: "400",
      },
      letterSpacing: {
        4: 0,
        5: 0,
        6: 0,
        true: 0,
      },
      face: {
        400: { normal: "Inter_400Regular" },
        600: { normal: "Inter_600SemiBold" },
        700: { normal: "Inter_700Bold" },
      },
    },
    heading: {
      family: "Poppins",
      size: {
        sm: 14,
        md: 16,
        lg: 20,
        xl: 28,
        xxl: 36,
        1: 11,
        2: 12,
        3: 13,
        4: 14,
        5: 15,
        6: 16,
        7: 20,
        8: 23,
        9: 30,
        10: 46,
        true: 20,
      },
      lineHeight: {
        sm: 20,
        md: 24,
        lg: 28,
        xl: 36,
        1: 16,
        2: 18,
        3: 20,
        4: 22,
        5: 22,
        6: 24,
        7: 28,
        8: 32,
        9: 40,
        10: 56,
        true: 28,
      },
      weight: {
        regular: "600",
        semibold: "600",
        bold: "700",
        4: "600",
        5: "600",
        6: "600",
        true: "600",
      },
      letterSpacing: {
        4: 0,
        5: 0,
        6: 0,
        true: -0.5,
      },
      face: {
        600: { normal: "Poppins_600SemiBold" },
        700: { normal: "Poppins_700Bold" },
      },
    },
  },
  shorthands: {
    px: "paddingHorizontal",
    py: "paddingVertical",
    p: "padding",
    m: "margin",
    mx: "marginHorizontal",
    my: "marginVertical",
    mt: "marginTop",
    mb: "marginBottom",
    ml: "marginLeft",
    mr: "marginRight",
    pt: "paddingTop",
    pb: "paddingBottom",
    pl: "paddingLeft",
    pr: "paddingRight",
    f: "flex",
    fd: "flexDirection",
    fw: "flexWrap",
    ai: "alignItems",
    jc: "justifyContent",
    bg: "backgroundColor",
    br: "borderRadius",
    boc: "borderColor",
    bw: "borderWidth",
    w: "width",
    h: "height",
    maw: "maxWidth",
    mah: "maxHeight",
    miw: "minWidth",
    mih: "minHeight",
    pos: "position",
    zi: "zIndex",
    ov: "overflow",
    op: "opacity",
  } as const,
  media: {
    xs: { maxWidth: 660 },
    sm: { maxWidth: 800 },
    md: { maxWidth: 1020 },
    lg: { maxWidth: 1280 },
    xl: { maxWidth: 1650 },
    xxl: { minWidth: 1651 },
    gtXs: { minWidth: 660 + 1 },
    gtSm: { minWidth: 800 + 1 },
    gtMd: { minWidth: 1020 + 1 },
    gtLg: { minWidth: 1280 + 1 },
  },
});

export type AppConfig = typeof config;

declare module "tamagui" {
  interface TamaguiCustomConfig extends AppConfig {}
}

export default config;

// Font assets export for useFonts
export const fontAssets = {
  Inter_400Regular,
  Inter_600SemiBold,
  Inter_700Bold,
  Poppins_600SemiBold,
  Poppins_700Bold,
};
